modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/saultsc/battle_showdown/issues"
license = "MPL-2.0"

[[mods]]
modId = "battle_showdown"
version = "${version}"
displayName = "Cobblemon: Battle Showdown"
authors = "Accieo"
description = '''
Pasture block can now be used as a utility block that gives Pokémon jobs!
'''
logoFile = "assets/battle_showdown/icon.png"

[[dependencies.battle_showdown]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.battle_showdown]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "battle_showdown.mixins.json"
