name: Discord Webhook Notification
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_INFO=$(git log -1 --pretty=format:'• [%h](https://github.com/'"$GITHUB_REPOSITORY"'/commit/%H) - %s by %an')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub",
            "embeds": [{
              "title": "🚀 New Push to Main!",
              "description": "**Repository:** `'"$GITHUB_REPOSITORY"'`\n**Committer:** `'"$GITHUB_ACTOR"'`\n\n**Latest Commit:**\n'"$COMMIT_INFO"'",
              "color": 3066993
            }]
          }' $DISCORD_WEBHOOK
